"""Build a PDF risk report with reportlab."""
from io import BytesIO
from django.utils import timezone

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, ListFlowable, ListItem
)

FIELD_LABELS = [
    ("Age", "age"),
    ("Sex", "get_sex_display"),
    ("Chest pain type", "get_chest_pain_type_display"),
    ("Resting BP (mmHg)", "resting_bp"),
    ("Cholesterol (mg/dL)", "cholesterol"),
    ("Fasting blood sugar", "get_fasting_bs_display"),
    ("Resting ECG", "get_resting_ecg_display"),
    ("Max heart rate", "max_hr"),
    ("Exercise angina", "get_exercise_angina_display"),
    ("Oldpeak (ST depression)", "oldpeak"),
    ("ST slope", "get_st_slope_display"),
]


def _value(obj, attr):
    v = getattr(obj, attr)
    return v() if callable(v) else v


def build_report_pdf(obj):
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=18 * mm, bottomMargin=18 * mm,
        title=f"Heart Risk Report #{obj.pk}",
    )

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle("Tiny", parent=styles["Normal"], fontSize=8, textColor=colors.grey))
    title_style = ParagraphStyle("Head", parent=styles["Title"], fontSize=20)

    is_risk = obj.result == 1
    result_text = "Heart Disease Risk Detected" if is_risk else "No Heart Disease Risk"
    result_hex = "#B91C1C" if is_risk else "#15803D"

    story = []
    story.append(Paragraph("HeartCare Predict - Risk Report", title_style))

    created = obj.created_at or timezone.now()
    who = obj.user.username if obj.user else "Guest"
    story.append(Paragraph(
        f"Report #{obj.pk} &nbsp;|&nbsp; User: {who} &nbsp;|&nbsp; "
        f"Generated: {created.strftime('%d %b %Y, %H:%M')}", styles["Tiny"]))
    story.append(Spacer(1, 10 * mm))

    story.append(Paragraph(
        f'<b>Prediction result:</b> <font color="{result_hex}"><b>{result_text}</b></font>',
        styles["Normal"]))
    story.append(Spacer(1, 6 * mm))

    rows = [["Parameter", "Value"]]
    for label, attr in FIELD_LABELS:
        rows.append([label, str(_value(obj, attr))])
    table = Table(rows, colWidths=[70 * mm, 90 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E293B")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F1F5F9")]),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(table)
    story.append(Spacer(1, 8 * mm))

    if is_risk:
        story.append(Paragraph("<b>Why this result - contributing factors</b>", styles["Normal"]))
        story.append(Spacer(1, 3 * mm))
        reasons = obj.risk_reasons or ["Model flagged elevated risk based on the overall profile."]
        story.append(ListFlowable(
            [ListItem(Paragraph(r, styles["Normal"])) for r in reasons],
            bulletType="bullet",
        ))
        story.append(Spacer(1, 8 * mm))

    story.append(Paragraph(
        "This report is generated by a machine-learning model for educational purposes only. "
        "It is not a medical diagnosis. Please consult a qualified doctor.", styles["Tiny"]))

    doc.build(story)
    pdf = buf.getvalue()
    buf.close()
    return pdf
