# Generated by Django 6.0.7 on 2026-07-13 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HeartPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "chest_pain_type",
                    models.CharField(
                        choices=[
                            ("ATA", "ATA"),
                            ("NAP", "NAP"),
                            ("ASY", "ASY"),
                            ("TA", "TA"),
                        ],
                        max_length=3,
                    ),
                ),
                ("resting_bp", models.IntegerField()),
                ("cholesterol", models.IntegerField()),
                ("fasting_bs", models.IntegerField(choices=[(0, "No"), (1, "Yes")])),
                (
                    "resting_ecg",
                    models.CharField(
                        choices=[("Normal", "Normal"), ("ST", "ST"), ("LVH", "LVH")],
                        max_length=10,
                    ),
                ),
                ("max_hr", models.IntegerField()),
                (
                    "exercise_angina",
                    models.CharField(choices=[("N", "No"), ("Y", "Yes")], max_length=1),
                ),
                ("oldpeak", models.FloatField()),
                (
                    "st_slope",
                    models.CharField(
                        choices=[("Up", "Up"), ("Flat", "Flat"), ("Down", "Down")],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
